#!/bin/bash


function download() {
    local records="^(a|aaaa|any|caa|cname|mx|ns|txt)$"
    local record="$1"

    if [ "$record" == "" ]; then
        record="cname"
    fi

    if grep -qP "$records" <<< "$record"; then
        local url="https://opendata.rapid7.com"
        local filename=`curl -s "$url/sonar.fdns_v2/" | grep -oP "sonar.*?_$record.json.gz"`

        local target="$url/$filename"
        echo "[+] Downloading $record file '$target'"
        echo
        wget "$target"
    fi
}


function list() {
    local provider="$1"

    if [ "$provider" != "" ]; then
        if grep -qP "$regex" <<< "$provider"; then
            echo "${!provider}"
        fi
    else
        for p in $providers; do echo $p; done
    fi
}


function load() {
    directory="providers"
    providers=`ls $directory`
    regex="^(`echo -n "$providers" | tr '\n' '|'`)$"

    for p in $providers; do
        declare -g "$p=`cat $directory/$p`"
    done
}


function search() {
    local submode="$1"
    local pattern="$2"
    local filename="$3"
    local filter="$pattern"
    local get="cat"

    if [ "$submode" == "all" ]; then
        for p in $providers; do
            echo "[+] $p"
            search "$p" "$pattern" "$filename"
        done
        return
    
    elif grep -qP "$regex" <<< "$submode"; then
        local subdomains=`echo "${!submode}" | grep -v '^$' | tr '\n' '|' | head -c -1`
        filter="\.($subdomains)\.?"

    elif [ "$submode" != "open" ]; then
        return

    fi

    if grep -qP "^http[s]?://" <<< "$filename"; then get="curl -L -s"; fi

    grep="grep"
    if [ "$COLOR" == "true" ]; then grep="$grep --color=always"; fi

    $get "$filename" \
    | gunzip \
    | $grep --line-buffered -P "$filter" \
    | $grep --line-buffered -P "$pattern" \
    | mawk -W interactive -F '"' '{print $8" --> "$16}'
}


load

mode="$1"

case "$mode" in
    download)
        record="$2"
        $mode "$record"
        ;;
    list)
        provider="$2"
        $mode "$provider"
        ;;
    search)
        submode="$2"
        pattern="$3"
        filename="$4"
        $mode "$submode" "$pattern" "$filename"
        ;;
esac
